apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: null
  name: cluster
spec:
  additionalTrustedCA:
    name: ""
  registrySources: {}
status: {}
