apiVersion: config.openshift.io/v1
kind: Project
metadata:
  creationTimestamp: null
  name: cluster
spec:
  projectRequestMessage: To provision Projects you must request access in https://labs.opentlc.com
    or https://rhpds.redhat.com
  projectRequestTemplate:
    name: project-request
status: {}
