apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  clusterNetwork:
  - cidr: 10.1.0.0/16
    hostPrefix: 23
  defaultNetwork:
    openshiftSDNConfig:
      mode: NetworkPolicy
    type: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
status: {}
